# Generated by Django 3.2.10 on 2023-07-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordb',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='doctordb',
            old_name='lastname',
            new_name='lname',
        ),
    ]
