# Generated by Django 3.2.10 on 2023-07-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20230729_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordb',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctordb',
            name='lname',
        ),
    ]
