# Generated by Django 3.2.10 on 2023-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20230730_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
