# Generated by Django 3.2.10 on 2023-08-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_doctordb_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctordb',
        ),
    ]
