# Generated by Django 3.2.10 on 2023-08-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_doctordb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
