# Generated by Django 4.2.5 on 2023-09-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_deptdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptdb',
            old_name='department',
            new_name='Department',
        ),
    ]
