# Generated by Django 4.2.5 on 2023-09-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_rename_department_deptdb_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptdb',
            old_name='Department',
            new_name='department',
        ),
    ]
