# Generated by Django 4.2.5 on 2023-09-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='appointmentdb',
        ),
    ]
