# Generated by Django 4.2.5 on 2023-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_rename_appointment_appointmentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdb',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
